version: "3"
services:
  issuer:
    #image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.8.0-rc0
    image: acapy-cache-redis
    build:
     context: ./
     dockerfile: ./docker/Dockerfile
    volumes:
      - ./configs:/home/indy/configs:ro,z
    ports:
      - "8150:8150"
      - "8151:8151"
    environment:
      ACAPY_ADMIN_API_KEY: ${ACAPY_ADMIN_API_KEY}
      ACAPY_ADMIN_INSECURE_MODE: false
      ACAPY_WALLET_STORAGE_CONFIG: '{"url":"${DATABASE}:5432","max_connections":5}'
      ACAPY_GENESIS_URL: ${ACAPY_GENESIS_URL}
      ACAPY_WALLET_STORAGE_CREDS: '{"account":"${ACCOUNT}","password":"${PASSWORD}","admin_account":"${ADMIN_ACCOUNT}","admin_password":"${ADMIN_PASSWORD}"}'
    #entrypoint: python -m cProfile -m aries_cloudagent
    command: >
      start
        --arg-file ./configs/issuer.yml
        --endpoint http://${ISSUER}:${EXPOSED_PORT}
        --genesis-url ${ACAPY_GENESIS_URL}
        --tails-server-base-url http://tails:6543
        --log-level debug
        --plugin-config-value redis_cache.connection="redis://${DATABASE:-redis-host}:6379/0"
        --plugin-config-value redis_cache.max_connections=90
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:8151/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      - tails

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=${ACAPY_GENESIS_URL}
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO
